#! /bin/sh

sxhkd &
xcompmgr -n &
xwallpaper --zoom ~/pictures/wallpapers/current/current.jpg
polybar example &
wal -i ~/pictures/wallpapers/current/current.jpg
xrdb ~/.Xresources

# bspc monitor LVDS1 -d I II III IV V VI VII VIII IX X
bspc monitor LVDS1 -d general web chat media scripting games school editing virtualization support

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a virtualbox desktop='^9' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
